### ISSUE TITLE
Not valid paths error

### ISSUE THREAD

**Issue by hoangphucITJP** [Bogdan-Lyashenko/codecrumbs#36]
Why does it say __Not valid paths__ though those paths do exist?
```
phuc_thai@linuxsws009:~/Documents/lottery-result-crawler$ l
main.py  requirements.txt
phuc_thai@linuxsws009:~/Documents/lottery-result-crawler$ codecrumbs -d ~/Documents/lottery-result-crawler -e ~/Documents/lottery-result-crawler/main.py 
>
> Codecrumbs magic begins!
>
> started with options: {"entryPoint":"/home/phuc_thai/Documents/lottery-result-crawler/main.py","projectDir":"/home/phuc_thai/Documents/lottery-result-crawler","clientPort":2018}
Not valid paths. Please enter valid path, next path does not exist: /home/phuc_thai/Documents/lottery-result-crawler, /home/phuc_thai/Documents/lottery-result-crawler/main.py
```

**Comment by Bogdan-Lyashenko** [comment]
Ho @hoangphucITJP , in order to make it work you need to use relative paths for project.

So, instead of
`phuc_thai@linuxsws009:~/Documents/lottery-result-crawler$ codecrumbs -d ~/Documents/lottery-result-crawler -e ~/Documents/lottery-result-crawler/main.py`

please try to do the following:
1) Go to `phuc_thai@linuxsws009:~/Documents/`
2) Run `codecrumbs -d lottery-result-crawler -e lottery-result-crawler/main.py` 
3) Should work just fine 🙂 

Thanks for the feedback, please come back to me if it helped.
I will make sure to add support of paths params in the format you tried it at first.

**Comment by hoangphucITJP** [comment]
Thank @Bogdan-Lyashenko, It works!

**Comment by Bogdan-Lyashenko** [comment]
Great!
